name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest
    name: Label PR based on files changed
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Label PR
        uses: p6m7g8-actions/p6-gh-pr-labeler@main
        with:
          gh_token: ${{ secrets.P6_A_GH_TOKEN }}
