name: Shellcheck

on:
  pull_request:
    branches: [main]
    paths:
      - gh-parallel

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Shellcheck
        run: shellcheck gh-parallel
